### PR TITLE
made the source more cross-compiler friendly

### PR DESCRIPTION
**Pull request by SamuraiCrow**
Signed-off-by: SamuraiCrow <samuraileumas@yahoo.com>

### CODE REVIEW

**Comment by SamuraiCrow** [comment]
I finally got it to build on MSYS2 with a few changes to the PATH variable.

**Comment by h5n1xp** [comment]
This is really exciting, I've not work on a project with external contributions like this before, so bare with me while I get to gips with merges.

**Review by h5n1xp — APPROVED** [review]
👍

**Comment by SamuraiCrow** [comment]
I think you need to close the pull request once the conflicts are resolved.

**Comment by h5n1xp** [comment]
Your changes were really helpful!

**Pull request closed without merging**
